# Generated by Django 2.1 on 2018-11-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('contact', models.CharField(blank=True, max_length=64)),
                ('notify', models.BooleanField(default=True)),
            ],
        ),
    ]
