# Generated by Django 2.1 on 2018-11-13 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 13, 18, 14, 22, 584920, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please provide your email address.', 'unique': 'An entry with this email exist.'}, max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
