# Generated by Django 2.1 on 2018-11-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20181114_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='timestamp',
            new_name='timestamp_registration',
        ),
    ]
