# Generated by Django 2.1 on 2018-11-16 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_entry_random_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='random_str',
        ),
        migrations.AddField(
            model_name='entry',
            name='random_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
