# Generated by Django 2.1 on 2018-11-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20181116_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='random_uuid',
        ),
    ]
