# Generated by Django 2.1 on 2018-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_entry_random_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='timestamp_registration',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(default='Hello', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(default='hello', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='organization',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
