# Generated by Django 2.1 on 2018-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20181120_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(error_messages={'required': 'Please provide your contact number', 'unique': 'An entry with this contact number already exists'}, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='first_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_name',
            field=models.CharField(max_length=1024),
        ),
    ]
